server:
  port: 7001

eureka:
  instance:
    #映射名
    hostname: eureka7001.com
    #    hostname: eureka
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
  ###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: false
    ###因为自己为注册中心 ,不会去在该应用中的检测服务
    fetch-registry: false
  server:
    #自我保护机制 关闭
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000